name: ci

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Build and Push
      env:
        REPOSITORY: dohq/bosh-env
        VERSION: ${{ steps.get_version.outputs.version }}
        DOCKER_BUILDKIT: 1
      run: |
        make build VERSION=$IMAGE_TAG IMAGE=$REPOSITORY
        make push VERSION=$IMAGE_TAG IMAGE=$REPOSITORY
        make cache VERSION=$IMAGE_TAG IMAGE=$REPOSITORY
